### ISSUE TITLE
Modifications to Draft.md

### ISSUE THREAD

**Issue by AhmadHamze** [ismailkoussa/market-website#2]
1. Change the name of the project, "final-project" is unacceptable (you can change it in the settings) 
2. All sentences need to be checked on Grammarly (Including the headers!)
3. All proper nouns should be capitalized (e.g. Python, Flask)
4. You should include images of the website (just like you did in the Readme file)
5. Python and Flask's installation should be added to the Readme file and the details of the project should be added in the Draf instead

**Comment by ismailkoussa** [comment]
Thanks! all done
